### ISSUE TITLE
Thunderbolt icons

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#1010]
For the FWUPD stuff, we need an icon `thunderbolt`. It looks like there's a fallback symbolic icon we're using from Adwaita, but it would be nice to have a proper icon for this

**Comment by hanaral** [comment]
Isn't the logo a copyright? I was considering giving it a shot

**Comment by Idan-A** [comment]
![path833](https://user-images.githubusercontent.com/43232607/113747771-04250680-9708-11eb-9623-b77d5d5901b2.png)
I did it 
if you like it I will send the svg file

**Comment by hanaral** [comment]
@danrabbit Is the icon going to be used for a settings plug? I want to be able to target the necessary sizes

**Comment by danrabbit** [comment]
Yeah the size we need here is 32px, but it would be nice to have other sizes and symbolic just in case

**Comment by Idan-A** [comment]
![Thunderbolt icons 32 px](https://user-images.githubusercontent.com/43232607/115142572-cfd41300-a042-11eb-8745-3e619c02d2b7.png)

**Comment by danrabbit** [comment]
@Idan-A Thank you for your proposal, but it doesn't resemble the Thunderbolt USB standard or follow the style of existing elementary icons.

You may want to check out this section of the HIG: https://elementary.io/docs/human-interface-guidelines#iconography

**Comment by hanaral** [comment]
I know no-one said it would be easy, but god damn the thunderbold icon sucks at small sizes.
![simpler](https://user-images.githubusercontent.com/58219504/115203631-8d1c4480-a0ef-11eb-8414-57288a59aa18.png)
![simplerx2](https://user-images.githubusercontent.com/58219504/115203652-90afcb80-a0ef-11eb-86e0-72c6a42bc86b.png)
The badge is courtesy of preferences-system-power, I used the same colour levels as the original yellow but with the blueberry palette instead. Unlike the power settings icon though, this bolt has 95% opacity rather than 100% because it's too big and looks unbalanced otherwise.

I initially wanted to something more unique metallic texture to the bolt like this:
![bolt](https://user-images.githubusercontent.com/58219504/115203884-d2407680-a0ef-11eb-94e4-a637b0f94805.png)
![boltx2](https://user-images.githubusercontent.com/58219504/115203897-d4a2d080-a0ef-11eb-9d2d-7ef738163fc8.png)
Maybe someone else could take the more unique bolt style and use it on a better backdrop, idk

I've also considered dumping the badge style entirely for something more akin to the firmware icon, which might make more sense to some people(?) thunderbolt is a brand like bluetooth and doesn't mean anything by itself. (nerdy folks may be able to guess from the arrow looking like the USB logo, but even that isn't very helpful)

@danrabbit If you think that this is a good start I'll open a PR and work my way through the icons (exams this week)
