### ISSUE TITLE
Redesign system-file-manager

### ISSUE THREAD

**Issue by danirabbit** [elementary/icons#1101]
### Problem

![system-file-manager](https://user-images.githubusercontent.com/7277719/165369214-a0d82124-8fb8-4b8d-a44c-38fd60301b03.png)

* The icon indicates `home`, but Files doesn't necessarily always open to `~/`
* The shape conflates it with a folder instead of an app
* The size is much shorter on the canvas than other app icons

### Proposal

* Avoid the `home` methaphor
* Consider a rounded square base like most other app icons

### Prior Art (Optional)

* It seems like blue is a pretty dominant color here in other file manager icons
* Including the spyglass metaphor is kind of interesting, but I'm not sure it's any more relevant than other apps that have search

## Chrome OS
![chrome](https://user-images.githubusercontent.com/7277719/165370493-80ae91c1-f0ea-4861-97c2-501c03aba882.png)

## GNOME
![gnome](https://user-images.githubusercontent.com/7277719/165370076-616ce8d8-f26e-422f-adff-cd8322ea26b9.png)

## iOS
![apple](https://user-images.githubusercontent.com/7277719/165369797-b17b0c55-8fc6-4210-b762-e5839e754844.jpeg)

## Windows
![windows](https://user-images.githubusercontent.com/7277719/165369928-15a921de-71b7-4b42-8ffe-a71047500d23.jpeg)

## Other

![](https://cdn.dribbble.com/users/915711/screenshots/5819494/media/cf8cef2e1940294ec5b856e75186c195.png?compress=1&resize=800x600&vertical=top)

![amaze](https://user-images.githubusercontent.com/7277719/165370341-51321b84-14cb-4647-bcfb-7fe219d78098.png)

![](https://github.com/ubuntu/yaru/blob/master/icons/Yaru/48x48@2x/apps/filemanager-app.png?raw=true)

**Comment by jeremypw** [comment]
The first "Other" example is interesting - nice and square and also suggests the ability to color tag folders.

**Comment by Arnwaltur** [comment]
I find the first "other" to be the most meaningful.
A flattened version, as the last "other", with a big well-centered magnifying glass would do the job.

**Comment by waldyrious** [comment]
Alternatively, the icon on top of the folder could be a cursor (hand or arrow), since it's arguably more common to navigate by clicking around than by searching.

Another option could be a tree representation, like this:
<img src="https://cdn4.iconfinder.com/data/icons/interface-52/100/icon.1-512.png" width="200"> <img src="https://banner2.cleanpng.com/20180426/rrq/kisspng-computer-icons-diagram-tree-view-organization-5ae1935f195a19.1076368015247327671039.jpg" width="200"> <img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/tree-structure-3938803-3268787.png" width="200">


either in front of the folder, something like this:

<img src="https://user-images.githubusercontent.com/478237/168251131-1435f453-e638-4362-be18-1faf1c7d5473.png" width="200">

...or below it:

<img src="https://user-images.githubusercontent.com/478237/168251228-f6bfe9e8-7dd5-47fe-89a7-9ea0dafce0cd.png" width="200">

...or instead of it altogether:

<img src="https://user-images.githubusercontent.com/478237/168250964-5033c7e1-acf1-4fe3-8971-74670fa3b6be.png" width="200">

**Comment by danielarrazola** [comment]
I made this to explain myself hehe

I think removing "home" icon from th icon is correct.

![rect51655](https://user-images.githubusercontent.com/99235118/174409454-8bfe0032-8566-497d-8bef-0f822572185c.png)

But I think we have to change the color of the icon for the default color of the files that are displayed for the first time when you open the File Manager. Elementary starts with this browny-yellowish folders color, so the user can quickly understand the reference between what the icon and how the files should look.

![rect51533](https://user-images.githubusercontent.com/99235118/174409679-4e9a2e6b-1ede-4647-8f2c-520054de6871.png)

I personally think adding more elements is unnecessary. The magnifying glass element i think is unnecessary too.

**Comment by JohnDumpling** [comment]
@danielarrazola I like the middle icons with the greyish and blue background:
![obrázok](https://user-images.githubusercontent.com/89086803/176660254-e78969e9-3324-415a-8bd9-618bd7cca703.png)
The elementary logo makes the icons look too busy and complicated. Search icon is fine, but plain folder is more universal.

**Comment by CandelaFierro** [comment]
A possible synthesis of the mentioned concepts:
![folderelementary2](https://user-images.githubusercontent.com/84086818/185830524-3022ed10-4c38-4290-ac28-c823a3611c65.png)

**Comment by LeBrick-Studio** [comment]
mixed feelings on this one tbh... it doesn't really fit the way folders look in eOS, and there wasn't any need making in blue

**Comment by LeBrick-Studio** [comment]
i think this concept looks more eye-pleasant and consistent with the previous icon https://github.com/elementary/icons/issues/1101#issuecomment-1171071703

just make the folder gray and put the search icon on it
