### ISSUE TITLE
Icon inside the play button not in center

### ISSUE THREAD

**Issue by ausdauerer** [elementary/icons#1232]
### What Happened?

The play icon within the button is slightly to the left. It is not causing any problems, just to improve the aesthetic.

![image](https://github.com/elementary/wingpanel/assets/60039285/401afa87-702e-4235-9bd4-e6241e87064c)

### Steps to Reproduce

* Play music
* Click on the sound button in the wingpanel
* Pause the music so that the play button is visible

### Expected Behavior

Icon in the center of the button

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by newhoa** [comment]
I also noticed a while back that the skip icons are off center. When I looked into this I thought it looked like it was intentionally that way so that skip and seek matched up if they change from one to the other in-place? (here is an example of [seek](https://github.com/elementary/icons/assets/1984060/ec4d90a5-e2de-4955-9a1f-ccf1aa37342e) and [skip](https://github.com/elementary/icons/assets/1984060/e12a58f9-658d-450c-999f-5c88ba682da3) where skip is edge-aligned in order for the arrows to match up) But I think in cases like OPs image, the skip icons also look slightly off center because of it.

I think the benefits of centering the skip icons outweigh the arrow alignment thing, but that's just my thoughts. Maybe if it were changed it would look a lot more off somewhere else.

Ironically, though, the play icon in OPs picture is actually centered and the others aren't; it's just that the weight-distribution of the play icon is heavily to the left which makes it look off. Just moving it a pixel off-center would make it look more centered.

Here is an example of centering the skip icons, and off-centering the play button:
![raligned2](https://github.com/elementary/icons/assets/1984060/75d94101-5326-4cd6-a28c-e214556ddc70)


But then of course the arrows of the seek and skip icons don't align in the case that they change from one to the other in-place.

If that's not a big deal and it's decided they should be centered I could do a PR for these, just let me know!
