### ISSUE TITLE
usb media device icon too big warning

### ISSUE THREAD

**Issue by duck7000** [elementary/icons#1243]
### What Happened?

Message: 13:35:27.456: Skipping build/elementary-xfce/devices/22/drive-removable-media-usb.png, size too big (24x24 instead of 22x22)

### Steps to Reproduce

upgrade elementay icons

### Expected Behavior

No warning and the right size icon

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Message: 13:35:27.456: Skipping build/elementary-xfce/devices/22/drive-removable-media-usb.png, size too big (24x24 instead of 22x22)
```

### Hardware Info

standard intel i59600k system with no extra gpu

**Comment by newhoa** [comment]
I'm going to go ahead an close this, as it does seem to be elementary-xfce and not elementary. Please report it to the issue tracker linked in the last comment. Thanks!

**Comment by duck7000** [comment]
Nope, elementary icons is selected but i have elementary-xfce installed.

![Screenshot_2024-02-15_19-25-17](https://github.com/elementary/icons/assets/15360048/e33e27ae-442b-446f-aa14-dd0fc64719d4)

yes i know it is a separate project but this happens with elementary icons selected so i reported here.

I'm using EndeavourOS (Arch linux like Manjaro)
I used yay to upgrade the system, this warning came by in the terminal

**Comment by newhoa** [comment]
Ok thanks for the extra info. I checked the [file on elementary-xfce](https://github.com/shimmerproject/elementary-xfce/blob/f963b3b70fc0558707c56868dbcc14992855217a/elementary-xfce/devices/22/drive-removable-media-usb.svg?short_path=dee9cb6) and it is 24px instead of the 22px it should be so it will have to be fixed over there.

Don't worry about re-reporting, I'll make a PR for it shortly. Thanks for the report!

**Comment by duck7000** [comment]
Thanks for your support!
