### ISSUE TITLE
Gnome disk utility has one of the icons wrong

### ISSUE THREAD

**Issue by uncertainquark** [elementary/icons#222]
Here is the popover showing the icon being referred to:
![screenshot from 2017-05-19 17 35 49](https://cloud.githubusercontent.com/assets/22585732/26259571/241b46be-3cb9-11e7-91e5-4898cbac5b0e.png)

A cross icon doesn't indicate the intended function.

**Comment by danrabbit** [comment]
This is a bug in GNOME Disks and can't be resolved in our icon set. It is requesting the wrong icon name

**Comment by cassidyjames** [comment]
Fwiw, GTK requests `process-stop-symbolic` as a fallback icon because someone thought that a stop sign (what the icon is in the GNOME Icon set) was a good fit for a menu, without regard for the very clear name. This is an upstream GTK bug, and visible here because Disks apparently doesn't set a Window Icon.

**Comment by cassidyjames** [comment]
I've filed the bug against GTK+ upstream https://bugzilla.gnome.org/show_bug.cgi?id=784624

**Comment by uncertainquark** [comment]
Thanks, as an end user who doesn't understand any of the technicalities, I really appreciate you taking the effort to file an appropriate bug for it!

**Comment by snwh** [comment]
This has been fixed :wink:
