### ISSUE TITLE
Confusing "open-menu" icon

### ISSUE THREAD

**Issue by RyanAfrish7** [elementary/icons#380]
Elementary uses a **gear icon for menu** in all the places. But most people from Android and a lot of other places are used to perceive it as "settings". It will be confusing for those people and it does not make much sense (to me at least) for the use of gear symbol. 

Hope the community comes with a better icon.

**Comment by cassidyjames** [comment]
@RyanAfrish7 the gear menu is not recommended anymore in apps made for elementary, but it is a strong historical convention. That said, I might be okay with something like what Android and Chrome use: a vertical ellipsis ⋮ icon (known there as the "overflow menu").

I want to avoid the hamburger icon ☰ because of its strong connotation with a side-navigation, whereas overflow menus are always a dropdown menu.

**Comment by cassidyjames** [comment]
That said, I also don't agree with the premise that the gear is inherently confusing, given that when it exists, it's consistent in function in elementary apps, has a tooltip, and is always located in the same place.

**Comment by RyanAfrish7** [comment]
I appreciate with the consistency throughout the system.

**Comment by danrabbit** [comment]
So it seems that now we're using `view-more` in a lot of places which is represented as vertical ellipsis to signify menus and the gear is pretty much only used in places where it does represent a settings menu or popover.

I'm going to close this for icons since semantically correct icons do exist already and if an app isn't using the correct icon then it's an issue with that app
