### ISSUE TITLE
Missing print icon

### ISSUE THREAD

**Issue by jwinnie-the-great** [elementary/icons#483]
When printing, one of the icons in the notification is present while the other is missing.

OS: elementaryOS 0.4.1 Loki

**Comment by danrabbit** [comment]
Can you get a screenshot of the issue please?

**Comment by jwinnie** [comment]
![printernotification](https://user-images.githubusercontent.com/20506149/39336856-7ef7f998-496e-11e8-9d93-999350a3f171.png)

**Comment by jwinnie** [comment]
![screenshot from 2018-04-26 16 27 00](https://user-images.githubusercontent.com/20506149/39336906-bdc0d5fa-496e-11e8-8de6-a1462a7e863e.png)

**Comment by danrabbit** [comment]
Can you maybe try to clarify a little bit what the issue seems to be? I can't see any missing icons in these screenshots

**Comment by danrabbit** [comment]
Ah okay. I'm not sure exactly what service sends these notifications, so I'll leave this issue open here for now, but there's nothing I can do in this repo to force another component to use a certain icon.

The issue of the square in the symbolic version of the icon is fixed in master though: https://github.com/elementary/icons/commit/c97460375820decb13482944aa09c96995282685

**Comment by waldyrious** [comment]
> The issue of the square in the symbolic version of the icon is fixed in master though: c974603

Specifically, PR #480

**Comment by julianlambert** [comment]
I think it would be appropriate to label this issue out of scope

**Comment by danirabbit** [comment]
I'm going to close this since the symbolic icon issue was resolved and this repo doesn't control which icons are used in notifications from other components
