### ISSUE TITLE
Providing an icon set option that mimics the design style of the logo

### ISSUE THREAD

**Issue by mrjohnc** [elementary/icons#629]
Hi

Are there any existing icon sets that mimic the design of the Elementary OS logo (monochrome, outline)? If so this would be a very nice icon set to include. 

The nearest I can find is Suru++ Asprómauros, however this is a dark theme, not a light theme so the icons are white rather than black https://www.gnome-look.org/p/1247483/

Thanks

**Comment by danrabbit** [comment]
Thanks for the suggestion! I'm going to close this issue as a "Design Conflict" because while elementary already provides a set of symbolic icons, that they're not used everywhere is intentional. We use color icons for tool items, categories, status, etc because the color conveys meaningful information and aids in quickly recognizing the importance/severity/context of a given shape.
