### ISSUE TITLE
unsafe network icon

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/icons#645]
![2018-08-27 00-24-52](https://user-images.githubusercontent.com/26849971/44631571-d6905200-a98f-11e8-8c62-d89c765d7cb6.png)
the icon unsafe network and safe network can be more black 
and my candidates for new icons
||
V
![lock](https://user-images.githubusercontent.com/26849971/44631608-5d452f00-a990-11e8-8a60-d080285f5e82.png)
![lock-disable](https://user-images.githubusercontent.com/26849971/44631609-5d452f00-a990-11e8-919d-1c65bca727b7.png)

**Comment by ItsPossibleAlready** [comment]
I can sent it in SVG format.

**Comment by danrabbit** [comment]
This is intentional. The line style here serves two purposes:
1. We want to really de-emphasize the lock here because the primary goal is to communicate that this channel is insecure. So the empty lock signifies that security is not present and helps to emphasize the red slash so it isn't drowned out by the solid form.
2. It works in context with the secure version which is filled in. Again the goal is contrast between the two states. Having a filled in form for the secure state helps emphasize the relationship and contrast against the insecured version.

For some context here are the two current icons together:
![insecure](https://user-images.githubusercontent.com/7277719/44670792-84275380-a9d8-11e8-9d6b-59e00633f763.png) ![secure](https://user-images.githubusercontent.com/7277719/44670793-84bfea00-a9d8-11e8-8fee-22c2c4234164.png)

You can see how the secured version is much more weighty than the insecure version and how the red slash is the dominant element in the insecure version.

Going to close this as a "Design conflict" since this was done with purpose
