### ISSUE TITLE
Complete icon set for Inkscape

### ISSUE THREAD

**Issue by wout** [elementary/icons#712]
While there are quite a few elementary icons present, there are still a lot of default icons in Inkscape:

![image](https://user-images.githubusercontent.com/107324/47872056-f0c23280-de0d-11e8-917b-381f80671c3f.png)

Is someone working on the missing ones? Because I'd love to see the set completed and I wouldn't mind contributing.

**Comment by danrabbit** [comment]
Since this isn't something that would likely be completed in a single PR, I've opened a new project [here](https://github.com/elementary/icons/projects/2) to track progress at.

I'm going to close this issue report just because it's really hard to track the progress of group issue reports, but please feel free to open reports for individual icons or icon families along with their icon names so that we can track progress more easily

**Comment by wout** [comment]
Great, thanks! First, I'll read up and make a list of all icons that should be created.
