### ISSUE TITLE
Complete Redesign of the Files Icons

### ISSUE THREAD

**Issue by Fatih20** [elementary/icons#815]
When you put the files icons next to the other elementary built-in app when you first install the OS. It feels out of place. It feels like it comes from a different icon set because of it's dimension, it's philosophy, etc. 

Most of the other icons is more square shaped. Most of the other icons have vibrant color. While I understand that files are system utility that by the eOS is outlined to use neutral color, I do think there are ways to make it less "bland" and more in line with the icons of other built-in apps.

Furthermore, I'm asking the developer, is this incoherency between the files icons and the other apps icons that prevented you from pinning the files app (which IMO what you should do) to the dock when you first installed the app.

**Comment by jeremypw** [comment]
There is a draft PR on this issue: https://github.com/elementary/icons/pull/813

**Comment by Fatih20** [comment]
That's just recoloring.

**Comment by jeremypw** [comment]
I thought there were some new designs suggested there but maybe I was mistaken - there has been some new designs put forward in the Slack channel as a result of that PR so the final version of that PR may do more than just recoloring.

**Comment by Fatih20** [comment]
Slack channel? Any way to access it?

**Comment by jeremypw** [comment]
I can ask the admins to send you an invitation if you like.

**Comment by micahilbery** [comment]
From the HIG:

https://elementary.io/docs/human-interface-guidelines#shape
- "Your icon should have a distinctive shape/silhouette to improve its recognition. This shape should not be too complicated, but the icon should not always be a rounded rectangle."

https://elementary.io/docs/human-interface-guidelines#color
- "it's best to reserve muted tones and grays for boring system icons."

As for why Files isn't pinned to the dock, it's because the workflow that we push for in elementary is that you use the app designed to manage the filetypes (ex. Photos for pictures or Music for audio) rather than use Files as a catch-all for sifting through all your data.
