### ISSUE TITLE
[question] Should the action symbolize an update arrow or a download arrow?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/icons#845]
The reference issue can be found here https://github.com/elementary/appcenter/pull/1147
For me the question: Which icon badge metaphor do you want to use in this context?

**Comment by cassidyjames** [comment]
We covered this pretty extensively in a chat, and the consensus seemed to be that a down arrow was more in line with other platforms (Android, for example) and make sense since an update will perform a download of data, and our download metaphor is a downward-facing arrow. 

The argument for an upward facing arrow is that it symbolizes the version increasing, but in my mind that's a much more abstract concept.
