### ISSUE TITLE
A non-Midori web browser icon

### ISSUE THREAD

**Issue by johnfactotum** [elementary/icons#893]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
The web browser icon is the very same one that used to be Midori's.

It's weird seeing the Midori icon used for Epiphany.

The green _thing_ around the globe doesn't really make sense with browsers that aren't Midori ("green" in Japanese).

What _is_ the green thing supposed to be, anyway?

**Describe the solution you'd like**

A new web browser/Epiphany icon without the green thing. In my opinion, it should either be something generic, not specific to specific browsers, or it should be something closer to the upstream icon.

**Existing work**

There was a very _Safari_ icon. In fact, it's still present in [README.md](https://github.com/elementary/icons/blob/master/README.md). It's probably too similar to Safari.

**Describe alternatives you've considered**

Just keep the current icon, I guess.

**Additional context**

The old Safari-like icon, still visible on README.md:
![Older Icon](https://camo.githubusercontent.com/6a0311f119f86f948af8011ce305e13d5dc9b261/687474703a2f2f656c656d656e746172792e696f2f696d616765732f646f63732f68756d616e2d696e746572666163652d67756964656c696e65732f69636f6e732f36342f696e7465726e65742d7765622d62726f777365722e737667)

The current icon:
![Current Icon](https://user-images.githubusercontent.com/50942278/81200163-1ad05400-8fb3-11ea-8d00-b45a5d0e11cc.png)

Current upstream icon:
![org gnome Epiphany](https://user-images.githubusercontent.com/50942278/81200547-a1853100-8fb3-11ea-8852-62c7d6561e6b.png)

**Comment by cassidyjames** [comment]
The globe-with-green icon has always been what we used for our default browser, and it has never been the upstream Midori icon. Originally it was inspired by the Midori concept (green plus a claw shape), but it has transcended that since we've been using it for the elementary-patched Epiphany for the past 3+ years.

We also want to avoid user confusion in changing the icon; if they're used to spotting that green half of the icon, removing it might be a bit jarring. However, at this point something that is visually similar would probably be easily identifiable by users with minimal confusion. The upstream icon as-is is wildly different from the elementary icon style, so would not be acceptable; we have also thought in the past that the mouse cursor on the icon is unnecessary and confusing. 

My vote would be: once we get to the point of shipping an Epiphany Flatpak, use a new elementary-styled icon for it. Maybe something like the blue Earth with the compass needle could be similar enough to the existing icon and sufficiently "web browser"-y while dropping the green claw.

**Comment by danrabbit** [comment]
The upstream Epiphany icon is now blue and green:
![](https://gitlab.gnome.org/GNOME/epiphany/-/raw/master/data/icons/hicolor/scalable/apps/org.gnome.Epiphany.svg)

Of note, the green portion is in the top left instead of the bottom right, but I would say that it is more similar to our browser metaphor now
