### ISSUE TITLE
add genie (.gs extension) icon 

### ISSUE THREAD

**Issue by Marukesu** [elementary/icons#904]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
 genie is a alternative-syntax to valac more similar to python, actually it's using the default text icon

**Comment by NikoKrause** [comment]
Any examples or proposals on how it's has to look like? Or how it does look in other themes? I don't know genie and a starting point would be nice

**Comment by Marukesu** [comment]
well it don't have a logo or some type of identification at all, i think that something like the vala mime but with a 'g' or 'gs' instead of 'v' would work.

**Comment by danirabbit** [comment]
Hey thanks for your suggestion. I'm really reluctant to add even more programming language file types. I think we are already supporting too many, especially because a lot of these logos don't look good at small sizes.

 I think I would rather have some generic programming language icons that are like "compiled language", "interpreted language", "markup language" and then symlink to these more generic icons. It's unlikely you'll mix programming languages in the same project so it's probably just more useful to figure out like which is a class file and which is like styles or xml or whatever

Gonna close as "Design conflict" since I want to reduce the number of programming language icons rather than expand it
