### ISSUE TITLE
Add an icon for Rust (.rs) files

### ISSUE THREAD

**Issue by apcamargo** [elementary/icons#979]
## Problem
ElementaryOS currently do not have a icon for files with the .rs extension, which are associated with the increasingly popular Rust language.

## Proposal
Add a icon for Rust files. One simple option would be to put the logo over the blank "paper" icon.

[Rust logo license](https://www.rust-lang.org/policies/media-guide):

> The Rust and Cargo logos (bitmap and vector) are owned by Mozilla and distributed under the terms of the Creative Commons Attribution license (CC-BY). This is the most permissive Creative Commons license, and allows reuse and modifications for any purpose. The restrictions are that distributors must “give appropriate credit, provide a link to the license, and indicate if changes were made.” Note that use of these logos, and the Rust and Cargo names, is also governed by trademark; our trademark policy is described below.

## Prior Art

![Screenshot from 2020-12-09 15 43 22](https://user-images.githubusercontent.com/22940964/101672984-4e85c780-3a35-11eb-83ab-0c5d5fc707a8.png)

**Comment by danirabbit** [comment]
Hey thanks for your suggestion. I'm really reluctant to add even more programming language file types. I think we are already supporting too many, especially because a lot of these logos don't look good at small sizes.

I think I would rather have some generic programming language icons that are like "compiled language", "interpreted language", "markup language" and then symlink to these more generic icons. It's unlikely you'll mix programming languages in the same project so it's probably just more useful to figure out like which is a class file and which is like styles or xml or whatever

Gonna close as "Design conflict" since I want to reduce the number of programming language icons rather than expand it
